"""Migracion de clientes

Revision ID: 102a10e0f0c8
Revises: 14403766e975
Create Date: 2026-06-07 20:52:01.251289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102a10e0f0c8'
down_revision = '14403766e975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
